

upsert into xinwei.res_kpi(id,name,dsttable) values('BTS000010','基站最佳接收语音包个数(求和)','xinwei.xinwei_BTS_VOICEPCK');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS000011','基站最佳接收语音包个数(最大)','xinwei.xinwei_BTS_VOICEPCK');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS000012','基站最佳接收语音包个数(最小)','xinwei.xinwei_BTS_VOICEPCK');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS000013','基站最佳接收语音包个数(平均)','xinwei.xinwei_BTS_VOICEPCK');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS000014','基站实际接收语音包个数(求和)','xinwei.xinwei_BTS_VOICEPCK');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS000015','基站实际接收语音包个数(最大)','xinwei.xinwei_BTS_VOICEPCK');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS000016','基站实际接收语音包个数(最小)','xinwei.xinwei_BTS_VOICEPCK');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS000017','基站实际接收语音包个数(平均)','xinwei.xinwei_BTS_VOICEPCK');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS000018','基站接收语音包ack率','xinwei.xinwei_BTS_VOICEPCK');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS000020','上行总带宽(求和)','xinwei.xinwei_BTS_BANDWIDTH');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS000021','上行总带宽(最大)','xinwei.xinwei_BTS_BANDWIDTH');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS000022','上行总带宽(最小)','xinwei.xinwei_BTS_BANDWIDTH');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS000023','上行总带宽(平均)','xinwei.xinwei_BTS_BANDWIDTH');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS000024','下行总带宽(求和)','xinwei.xinwei_BTS_BANDWIDTH');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS000025','下行总带宽(最大)','xinwei.xinwei_BTS_BANDWIDTH');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS000026','下行总带宽(最小)','xinwei.xinwei_BTS_BANDWIDTH');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS000027','下行总带宽(平均)','xinwei.xinwei_BTS_BANDWIDTH');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS000030','上行空闲信道数(求和)','xinwei.xinwei_BTS_CHANNEL');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS000031','上行空闲信道数(最大)','xinwei.xinwei_BTS_CHANNEL');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS000032','上行空闲信道数(最小)','xinwei.xinwei_BTS_CHANNEL');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS000033','上行空闲信道数(平均)','xinwei.xinwei_BTS_CHANNEL');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS000034','下行空闲信道数(求和)','xinwei.xinwei_BTS_CHANNEL');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS000035','下行空闲信道数(最大)','xinwei.xinwei_BTS_CHANNEL');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS000036','下行空闲信道数(最小)','xinwei.xinwei_BTS_CHANNEL');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS000037','下行空闲信道数(平均)','xinwei.xinwei_BTS_CHANNEL');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS000038','上行占用信道数(求和)','xinwei.xinwei_BTS_CHANNEL');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS000039','上行占用信道数(最大)','xinwei.xinwei_BTS_CHANNEL');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS0000310', '上行占用信道数(最小)','xinwei.xinwei_BTS_CHANNEL');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS0000311', '上行占用信道数(平均)','xinwei.xinwei_BTS_CHANNEL');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS0000312', '下行占用信道数(求和)','xinwei.xinwei_BTS_CHANNEL');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS0000313', '下行占用信道数(最大)','xinwei.xinwei_BTS_CHANNEL');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS0000314', '下行占用信道数(最小)','xinwei.xinwei_BTS_CHANNEL');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS0000315', '下行占用信道数(平均)','xinwei.xinwei_BTS_CHANNEL');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS000040','DAC异常释放次数(求和)','xinwei.xinwei_BTS_DAC');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS000041','DAC成功建立次数(求和)','xinwei.xinwei_BTS_DAC');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS000042','DAC掉线率','xinwei.xinwei_BTS_DAC');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS000050','L1接收的FEC块数(求和)','xinwei.xinwei_BTS_FEC');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS000051','L1接收的FEC坏块数(求和)','xinwei.xinwei_BTS_FEC');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS000052','L1接收的FEC可恢复块数(求和)', 'xinwei.xinwei_BTS_FEC');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS000053','上行FEC块错误率" ','xinwei.xinwei_BTS_FEC');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS000054','上行FEC块可恢复率','xinwei.xinwei_BTS_FEC');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS000060','基站发送重传ARQ个数(求和)','xinwei.xinwei_BTS_ARQ');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS000061','基站接收重传ARQ个数(求和)','xinwei.xinwei_BTS_ARQ');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS000062','基站发送ARQ个数(求和)','xinwei.xinwei_BTS_ARQ');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS000063','基站接收ARQ个数(求和)','xinwei.xinwei_BTS_ARQ');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS000064','发送ARQ重传率','xinwei.xinwei_BTS_ARQ');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS000065','接收ARQ重传率','xinwei.xinwei_BTS_ARQ');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS000070','RA接入次数(求和)','xinwei.xinwei_BTS_RA');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS000071','RA接入成功次数(求和)','xinwei.xinwei_BTS_RA');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS000072','RA MAC PDU的CRC校验通过次数(求和)', 'xinwei.xinwei_BTS_RA');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS000073','RA MAC PDU CRC校验通过率','xinwei.xinwei_BTS_RA');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS000074','RA信道占用率','xinwei.xinwei_BTS_RA');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS000080','睡眠寻呼请求1次寻呼成功次数(求和)', 'xinwei.xinwei_BTS_PAGING');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS000081','睡眠寻呼请求2次寻呼成功次数(求和)', 'xinwei.xinwei_BTS_PAGING');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS000082','睡眠寻呼请求3次寻呼成功次数(求和)', 'xinwei.xinwei_BTS_PAGING');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS000083','睡眠寻呼请求4次寻呼成功次数(求和)', 'xinwei.xinwei_BTS_PAGING');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS000084','睡眠寻呼请求5次寻呼成功次数(求和)', 'xinwei.xinwei_BTS_PAGING');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS000085','非睡眠寻呼请求1次寻呼成功次数(求和)','xinwei.xinwei_BTS_PAGING');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS000086','非睡眠寻呼请求2次寻呼成功次数(求和)','xinwei.xinwei_BTS_PAGING');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS000087','非睡眠寻呼请求3次寻呼成功次数(求和)','xinwei.xinwei_BTS_PAGING');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS000088','非睡眠寻呼请求大于3次寻呼成功次数(求和)', 'xinwei.xinwei_BTS_PAGING');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS000089','睡眠寻呼建立会话失败次数(求和)', 'xinwei.xinwei_BTS_PAGING');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS0000810', '非睡眠寻呼建立会话失败次数(求和)','xinwei.xinwei_BTS_PAGING');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS000811','寻呼建立会话总次数(求和)', 'xinwei.xinwei_BTS_PAGING');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS000812','寻呼成功率','xinwei.xinwei_BTS_PAGING');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS00090','下行信噪比统计量分布 (-∞,4)(求和)', 'xinwei.xinwei_BTS_SNROUTAGE');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS00091','下行信噪比统计量分布[4,8)(求和)', 'xinwei.xinwei_BTS_SNROUTAGE');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS00092','下行信噪比统计量分布[8,12)(求和)','xinwei.xinwei_BTS_SNROUTAGE');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS00093','下行信噪比统计量分布[12,16)(求和)','xinwei.xinwei_BTS_SNROUTAGE');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS00094','下行信噪比统计量分布[16,20)(求和)','xinwei.xinwei_BTS_SNROUTAGE');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS00095','下行信噪比统计量分布[20,+∞)(求和)','xinwei.xinwei_BTS_SNROUTAGE');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS00096','下行信噪比差比例','xinwei.xinwei_BTS_SNROUTAGE');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS00100','接收信号强度分布(-∞,-100)(求和)', 'xinwei.xinwei_BTS_PREAMBLE');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS00101','接收信号强度分布[-100,-90)(求和)','xinwei.xinwei_BTS_PREAMBLE');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS00102','接收信号强度分布[-90,-80)(求和)', 'xinwei.xinwei_BTS_PREAMBLE');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS00103','接收信号强度分布[-80,-70)(求和)', 'xinwei.xinwei_BTS_PREAMBLE');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS00104','接收信号强度分布[-70,-60)(求和)', 'xinwei.xinwei_BTS_PREAMBLE');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS00105','接收信号强度分布[-60,-50)(求和)', 'xinwei.xinwei_BTS_PREAMBLE');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS00106','接收信号强度分布[-50,-40)(求和)', 'xinwei.xinwei_BTS_PREAMBLE');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS00107','接收信号强度分布[-40,-30)(求和)', 'xinwei.xinwei_BTS_PREAMBLE');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS00108','接收信号强度分布[-30,-20)(求和)', 'xinwei.xinwei_BTS_PREAMBLE');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS00109','接收信号强度分布[-20,+∞)(求和)','xinwei.xinwei_BTS_PREAMBLE');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS001010','接收信号强度弱比','xinwei.xinwei_BTS_PREAMBLE');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS00110','上行CI分布 (-∞,10)(求和)','xinwei.xinwei_BTS_CI');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS00111','上行CI分布[10,20)(求和)','xinwei.xinwei_BTS_CI');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS00112','上行CI分布[20,30)(求和)','xinwei.xinwei_BTS_CI');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS00113','上行CI分布[30,40)(求和)','xinwei.xinwei_BTS_CI');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS00114','上行CI分布[40,50)(求和)','xinwei.xinwei_BTS_CI');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS00115','上行CI分布[50,60)(求和)','xinwei.xinwei_BTS_CI');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS00116','上行CI分布[60,+∞)(求和)','xinwei.xinwei_BTS_CI');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS00117','上行CI均值','xinwei.xinwei_BTS_CI');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS00118','上行CI高比例','xinwei.xinwei_BTS_CI');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS00119','下行CI分布 (-∞,10)(求和)','xinwei.xinwei_BTS_CI');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS001110','下行CI分布[10,20)(求和)', 'xinwei.xinwei_BTS_CI');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS001111','下行CI分布[20,30)(求和)', 'xinwei.xinwei_BTS_CI');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS001112','下行CI分布[30,40)(求和)', 'xinwei.xinwei_BTS_CI');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS001113','下行CI分布[40,50)(求和)', 'xinwei.xinwei_BTS_CI');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS001114','下行CI分布[50,60)(求和)', 'xinwei.xinwei_BTS_CI');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS001115','下行CI分布[60,+∞)(求和)', 'xinwei.xinwei_BTS_CI');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS001116','下行CI均值','xinwei.xinwei_BTS_CI');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS001117','下行CI高比例','xinwei.xinwei_BTS_CI');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS001118','上行CI绝对差分布 (-∞,5)(求和)','xinwei.xinwei_BTS_CI');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS001119','上行CI绝对差分布 [5,10)(求和)','xinwei.xinwei_BTS_CI');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS001120','上行CI绝对差分布 [10,15)(求和)', 'xinwei.xinwei_BTS_CI');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS001121','上行CI绝对差分布 [15,20)(求和)', 'xinwei.xinwei_BTS_CI');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS001122','上行CI绝对差分布 [20,25)(求和)', 'xinwei.xinwei_BTS_CI');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS001123','上行CI绝对差分布 [25,30)(求和)', 'xinwei.xinwei_BTS_CI');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS001124','上行CI绝对差分布 [30,+∞)(求和)', 'xinwei.xinwei_BTS_CI');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS001125','下行CI高比例','xinwei.xinwei_BTS_CI');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS001126','下行CI绝对差分布 (-∞,5)(求和)','xinwei.xinwei_BTS_CI');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS001127','下行CI绝对差分布 [5,10)(求和)','xinwei.xinwei_BTS_CI');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS001128','下行CI绝对差分布 [10,15)(求和)', 'xinwei.xinwei_BTS_CI');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS001129','下行CI绝对差分布 [15,20)(求和)', 'xinwei.xinwei_BTS_CI');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS001130','下行CI绝对差分布 [20,25)(求和)', 'xinwei.xinwei_BTS_CI');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS001131','下行CI绝对差分布 [25,30)(求和)', 'xinwei.xinwei_BTS_CI');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS001132','下行CI绝对差分布 [30,+∞)(求和)', 'xinwei.xinwei_BTS_CI');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS001133','下行CI高比例','xinwei.xinwei_BTS_CI');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS00120','源基站进入ByFrame请求次数(求和)','xinwei.xinwei_BTS_BYFRAME');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS00121','源基站退出ByFrame请求次数(求和)', 'xinwei.xinwei_BTS_BYFRAME');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS00122','源基站ByFrame正常率','xinwei.xinwei_BTS_BYFRAME');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS00123','目标基站进入ByFrame请求次数(求和)', 'xinwei.xinwei_BTS_BYFRAME');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS00124','目标基站退出ByFrame请求次数(求和)', 'xinwei.xinwei_BTS_BYFRAME');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS00125','目标基ByFrame正常率','xinwei.xinwei_BTS_BYFRAME');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS00126','源基站ByFrame平均时长','xinwei.xinwei_BTS_BYFRAME');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS00127','目标基站ByFrame平均时长','xinwei.xinwei_BTS_BYFRAME');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS00128','源基站ByFrame最大时长','xinwei.xinwei_BTS_BYFRAME');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS00129','目标基站ByFrame最大时长','xinwei.xinwei_BTS_BYFRAME');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS00130','时隙1下行总功率(求和)','xinwei.xinwei_BTS_TSPWR');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS00131','时隙1下行总功率(最大)','xinwei.xinwei_BTS_TSPWR');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS00132','时隙1下行总功率(最小)','xinwei.xinwei_BTS_TSPWR');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS00133','时隙1下行总功率(平均)','xinwei.xinwei_BTS_TSPWR');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS00134','时隙2下行总功率(求和)','xinwei.xinwei_BTS_TSPWR');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS00135','时隙2下行总功率(最大)','xinwei.xinwei_BTS_TSPWR');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS00136','时隙2下行总功率(最小)','xinwei.xinwei_BTS_TSPWR');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS00137','时隙2下行总功率(平均)','xinwei.xinwei_BTS_TSPWR');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS00138','时隙3下行总功率(求和)','xinwei.xinwei_BTS_TSPWR');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS00139','时隙3下行总功率(最大)','xinwei.xinwei_BTS_TSPWR');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS001310','时隙3下行总功率(最小)','xinwei.xinwei_BTS_TSPWR');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS001311','时隙3下行总功率(平均)','xinwei.xinwei_BTS_TSPWR');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS001312','时隙4下行总功率(求和)','xinwei.xinwei_BTS_TSPWR');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS001313','时隙4下行总功率(最大)','xinwei.xinwei_BTS_TSPWR');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS001314','时隙4下行总功率(最小)','xinwei.xinwei_BTS_TSPWR');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS001315','时隙4下行总功率(平均)','xinwei.xinwei_BTS_TSPWR');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS001316','时隙5下行总功率(求和)','xinwei.xinwei_BTS_TSPWR');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS001317','时隙5下行总功率(最大)','xinwei.xinwei_BTS_TSPWR');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS001318','时隙5下行总功率(最小)','xinwei.xinwei_BTS_TSPWR');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS001319','时隙5下行总功率(平均)','xinwei.xinwei_BTS_TSPWR');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS001320','时隙6下行总功率(求和)','xinwei.xinwei_BTS_TSPWR');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS001321','时隙6下行总功率(最大)','xinwei.xinwei_BTS_TSPWR');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS001322','时隙6下行总功率(最小)','xinwei.xinwei_BTS_TSPWR');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS001323','时隙6下行总功率(平均)','xinwei.xinwei_BTS_TSPWR');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS001324','时隙7下行总功率(求和)','xinwei.xinwei_BTS_TSPWR');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS001325','时隙7下行总功率(最大)','xinwei.xinwei_BTS_TSPWR');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS001326','时隙7下行总功率(最小)','xinwei.xinwei_BTS_TSPWR');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS001327','时隙7下行总功率(平均)','xinwei.xinwei_BTS_TSPWR');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS001328','时隙1下行总消耗功率(求和)','xinwei.xinwei_BTS_TSPWR');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS001329','时隙1下行总消耗功率(最大)','xinwei.xinwei_BTS_TSPWR');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS001330','时隙1下行总消耗功率(最小)','xinwei.xinwei_BTS_TSPWR');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS001331','时隙1下行总消耗功率(平均)','xinwei.xinwei_BTS_TSPWR');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS001332','时隙2下行总消耗功率(求和)','xinwei.xinwei_BTS_TSPWR');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS001333','时隙2下行总消耗功率(最大)','xinwei.xinwei_BTS_TSPWR');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS001334','时隙2下行总消耗功率(最小)','xinwei.xinwei_BTS_TSPWR');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS001335','时隙2下行总消耗功率(平均)','xinwei.xinwei_BTS_TSPWR');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS001336','时隙3下行总消耗功率(求和)','xinwei.xinwei_BTS_TSPWR');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS001337','时隙3下行总消耗功率(最大)','xinwei.xinwei_BTS_TSPWR');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS001338','时隙3下行总消耗功率(最小)','xinwei.xinwei_BTS_TSPWR');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS001339','时隙3下行总消耗功率(平均)','xinwei.xinwei_BTS_TSPWR');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS001340','时隙4下行总消耗功率(求和)','xinwei.xinwei_BTS_TSPWR');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS001341','时隙4下行总消耗功率(最大)','xinwei.xinwei_BTS_TSPWR');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS001342','时隙4下行总消耗功率(最小)','xinwei.xinwei_BTS_TSPWR');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS001343','时隙4下行总消耗功率(平均)','xinwei.xinwei_BTS_TSPWR');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS001344','时隙5下行总消耗功率(求和)','xinwei.xinwei_BTS_TSPWR');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS001345','时隙5下行总消耗功率(最大)','xinwei.xinwei_BTS_TSPWR');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS001346','时隙5下行总消耗功率(最小)','xinwei.xinwei_BTS_TSPWR');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS001347','时隙5下行总消耗功率(平均)','xinwei.xinwei_BTS_TSPWR');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS001348','时隙6下行总消耗功率(求和)','xinwei.xinwei_BTS_TSPWR');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS001349','时隙6下行总消耗功率(最大)','xinwei.xinwei_BTS_TSPWR');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS001350','时隙6下行总消耗功率(最小)','xinwei.xinwei_BTS_TSPWR');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS001351','时隙6下行总消耗功率(平均)','xinwei.xinwei_BTS_TSPWR');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS001352','时隙7下行总消耗功率(求和)','xinwei.xinwei_BTS_TSPWR');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS001353','时隙7下行总消耗功率(最大)','xinwei.xinwei_BTS_TSPWR');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS001354','时隙7下行总消耗功率(最小)','xinwei.xinwei_BTS_TSPWR');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS001355','时隙7下行总消耗功率(平均)','xinwei.xinwei_BTS_TSPWR');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS001356','下行总功率占用比例','xinwei.xinwei_BTS_TSPWR');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS00140','基站发送广播包和组播包个数(求和)', 'xinwei.xinwei_BTS_DATAPCK');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS00141','基站接收广播包和组播包个数(求和)','xinwei.xinwei_BTS_DATAPCK');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS00142','基站转发数据包个数(求和)', 'xinwei.xinwei_BTS_DATAPCK');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS00143','基站数据包转发速率','xinwei.xinwei_BTS_DATAPCK');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS00144','基站隧道转发数据包个数(求和)','xinwei.xinwei_BTS_DATAPCK');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS00145','基站隧道数据包转发速率','xinwei.xinwei_BTS_DATAPCK');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS00150','基站网口发送吞吐率(求和)','xinwei.xinwei_BTS_THROUGHPUT');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS00151','基站网口发送吞吐率(最大)','xinwei.xinwei_BTS_THROUGHPUT');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS00152','基站网口发送吞吐率(最小)','xinwei.xinwei_BTS_THROUGHPUT');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS00153','基站网口发送吞吐率(平均)','xinwei.xinwei_BTS_THROUGHPUT');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS00154','基站网口接收吞吐率(求和)','xinwei.xinwei_BTS_THROUGHPUT');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS00155','基站网口接收吞吐率(最大)','xinwei.xinwei_BTS_THROUGHPUT');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS00156','基站网口接收吞吐率(最小)','xinwei.xinwei_BTS_THROUGHPUT');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS00157','基站网口接收吞吐率(平均)','xinwei.xinwei_BTS_THROUGHPUT');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS00158','基站网口总吞吐率(求和)','xinwei.xinwei_BTS_THROUGHPUT');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS00159','基站网口总吞吐率(最大)','xinwei.xinwei_BTS_THROUGHPUT');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS001510','基站网口总吞吐率(最小)','xinwei.xinwei_BTS_THROUGHPUT');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS001511','基站网口总吞吐率(平均)','xinwei.xinwei_BTS_THROUGHPUT');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS001512','基站隧道发送吞吐率(求和)', 'xinwei.xinwei_BTS_THROUGHPUT');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS001513','基站隧道发送吞吐率(最大)', 'xinwei.xinwei_BTS_THROUGHPUT');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS001514','基站隧道发送吞吐率(最小)', 'xinwei.xinwei_BTS_THROUGHPUT');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS001515','基站隧道发送吞吐率(平均)', 'xinwei.xinwei_BTS_THROUGHPUT');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS001516','基站隧道接收吞吐率(求和)', 'xinwei.xinwei_BTS_THROUGHPUT');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS001517','基站隧道接收吞吐率(最大)', 'xinwei.xinwei_BTS_THROUGHPUT');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS001518','基站隧道接收吞吐率(最小)', 'xinwei.xinwei_BTS_THROUGHPUT');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS001519','基站隧道接收吞吐率(平均)', 'xinwei.xinwei_BTS_THROUGHPUT');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS001520','基站隧道总吞吐率(求和)','xinwei.xinwei_BTS_THROUGHPUT');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS001521','基站隧道总吞吐率(最大)','xinwei.xinwei_BTS_THROUGHPUT');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS001522','基站隧道总吞吐率(最小)','xinwei.xinwei_BTS_THROUGHPUT');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS001523','基站隧道总吞吐率(平均)','xinwei.xinwei_BTS_THROUGHPUT');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS00160','基站与主SAG握手超时次数(求和)','xinwei.xinwei_BTS_HANDSHAKE');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS00161','基站与主SAG握手超时次数(最大)','xinwei.xinwei_BTS_HANDSHAKE');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS00162','基站与主SAG握手超时次数(平均)','xinwei.xinwei_BTS_HANDSHAKE');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS00163','基站与主SAG握手平均时延(求和)','xinwei.xinwei_BTS_HANDSHAKE');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS00164','基站与主SAG握手平均时延(最大)','xinwei.xinwei_BTS_HANDSHAKE');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS00165','基站与主SAG握手平均时延(平均)','xinwei.xinwei_BTS_HANDSHAKE');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS00166','基站与备SAG握手超时次数(求和)','xinwei.xinwei_BTS_HANDSHAKE');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS00167','基站与备SAG握手超时次数(最大)','xinwei.xinwei_BTS_HANDSHAKE');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS00168','基站与备SAG握手超时次数(平均)','xinwei.xinwei_BTS_HANDSHAKE');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS00169','基站与备SAG握手平均时延(求和)','xinwei.xinwei_BTS_HANDSHAKE');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS001610','基站与备SAG握手平均时延(最大)','xinwei.xinwei_BTS_HANDSHAKE');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS001611','基站与备SAG握手平均时延(平均)','xinwei.xinwei_BTS_HANDSHAKE');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS00170','OAM注册请求次数(求和)','xinwei.xinwei_BTS_OAM');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS00171','OAM注册成功次数(求和)','xinwei.xinwei_BTS_OAM');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS00172','OAM注册成功率','xinwei.xinwei_BTS_OAM');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS00173','OAM重复注册间隔(求和)','xinwei.xinwei_BTS_OAM');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS00174','OAM重复注册次数(求和)','xinwei.xinwei_BTS_OAM');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS00175','OAM重复注册平均间隔','xinwei.xinwei_BTS_OAM');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS00180','数据服务用户数(平均)','xinwei.xinwei_BTS_USERS');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS00181','数据服务用户数(最大)','xinwei.xinwei_BTS_USERS');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS00182','以本基站为锚且在本基站下用户数(平均)', 'xinwei.xinwei_BTS_USERS');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS00183','以本基站为锚且在本基站下用户数(最大)', 'xinwei.xinwei_BTS_USERS');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS00184','以本基站为锚且在本基站下用户数(最小)', 'xinwei.xinwei_BTS_USERS');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS00185','以本基站为锚但不在本基站下用户数(平均)','xinwei.xinwei_BTS_USERS');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS00186','以本基站为锚但不在本基站下用户数(最大)','xinwei.xinwei_BTS_USERS');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS00187','以本基站为锚但不在本基站下用户数(最小)','xinwei.xinwei_BTS_USERS');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS00188','以其他基站为锚且在本基站下用户数(平均)','xinwei.xinwei_BTS_USERS');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS00189','以其他基站为锚且在本基站下用户数(最大)','xinwei.xinwei_BTS_USERS');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS001810','以其他基站为锚且在本基站下用户数(最小)','xinwei.xinwei_BTS_USERS');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS001811','离开用户数(求和)','xinwei.xinwei_BTS_USERS');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS001812','OAM注册成功用户数(求和)','xinwei.xinwei_BTS_USERS');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS001813','驻留用户数(求和)','xinwei.xinwei_BTS_USERS');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS001814','用户驻留时长(求和','xinwei.xinwei_BTS_USERS');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS001815','用户平均驻留时长','xinwei.xinwei_BTS_USERS');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS001816','数据用户个数(平均)','xinwei.xinwei_BTS_USERS');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS001817','数据用户个数(最大)','xinwei.xinwei_BTS_USERS');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS001818','数据用户个数(最小)','xinwei.xinwei_BTS_USERS');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS001819','语音用户个数(平均)','xinwei.xinwei_BTS_USERS');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS001820','语音用户个数(最大)','xinwei.xinwei_BTS_USERS');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS001821','语音用户个数(最小)','xinwei.xinwei_BTS_USERS');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS001822','在线终端个数(平均)','xinwei.xinwei_BTS_USERS');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS001823','在线终端个数(最大)','xinwei.xinwei_BTS_USERS');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS001824','在线终端个数(最小)','xinwei.xinwei_BTS_USERS');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS00190','数据业务寻呼请求次数(求和)','xinwei.xinwei_BTS_SERVICE');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS00191','数据业务寻呼请求次数(平均)','xinwei.xinwei_BTS_SERVICE');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS00192','数据业务寻呼请求次数(最大)','xinwei.xinwei_BTS_SERVICE');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS00193','数据业务寻呼请求次数(最小)','xinwei.xinwei_BTS_SERVICE');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS00194','数据业务寻呼成功次数(求和)','xinwei.xinwei_BTS_SERVICE');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS00195','数据业务寻呼成功次数(平均)','xinwei.xinwei_BTS_SERVICE');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS00196','数据业务寻呼成功次数(最大)','xinwei.xinwei_BTS_SERVICE');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS00197','数据业务寻呼成功次数(最小)','xinwei.xinwei_BTS_SERVICE');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS00198','语音业务寻呼请求次数(求和)','xinwei.xinwei_BTS_SERVICE');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS00199','语音业务寻呼请求次数(平均)','xinwei.xinwei_BTS_SERVICE');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS001910','语音业务寻呼请求次数(最大)','xinwei.xinwei_BTS_SERVICE');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS001911','语音业务寻呼请求次数(最小)','xinwei.xinwei_BTS_SERVICE');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS001912','语音业务寻呼成功次数(求和)','xinwei.xinwei_BTS_SERVICE');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS001913','语音业务寻呼成功次数(平均)','xinwei.xinwei_BTS_SERVICE');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS001914','语音业务寻呼成功次数(最大)','xinwei.xinwei_BTS_SERVICE');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS001915','语音业务寻呼成功次数(最小)','xinwei.xinwei_BTS_SERVICE');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS001916','单基站数据业务流量(求和)', 'xinwei.xinwei_BTS_SERVICE');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS001917','单基站数据业务流量(平均)', 'xinwei.xinwei_BTS_SERVICE');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS001918','单基站数据业务流量(最大)', 'xinwei.xinwei_BTS_SERVICE');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS001919','单基站数据业务流量(最小)', 'xinwei.xinwei_BTS_SERVICE');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS001920','单基站数据业务在线时长(求和)','xinwei.xinwei_BTS_SERVICE');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS001921','单基站数据业务在线时长(平均)','xinwei.xinwei_BTS_SERVICE');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS001922','单基站数据业务在线时长(最大)','xinwei.xinwei_BTS_SERVICE');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS001923','单基站数据业务在线时长(最小)','xinwei.xinwei_BTS_SERVICE');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS001924','数据业务掉线次数(求和)','xinwei.xinwei_BTS_SERVICE');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS001925','数据业务掉线次数(平均)','xinwei.xinwei_BTS_SERVICE');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS001926','数据业务掉线次数(最大)','xinwei.xinwei_BTS_SERVICE');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS001927','数据业务掉线次数(最小)','xinwei.xinwei_BTS_SERVICE');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS00200','切入总次数(平均)','xinwei.xinwei_BTS_OTHER');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS00201','切入总次数(最大)','xinwei.xinwei_BTS_OTHER');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS00202','切入总次数(最小)','xinwei.xinwei_BTS_OTHER');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS00203','切出总次数(平均)','xinwei.xinwei_BTS_OTHER');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS00204','切出总次数(最大)','xinwei.xinwei_BTS_OTHER');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS00205','切出总次数(最小)','xinwei.xinwei_BTS_OTHER');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS00206','同频匹配个数(最大)','xinwei.xinwei_BTS_OTHER');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS00207','同频匹配个数(最小)','xinwei.xinwei_BTS_OTHER');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS00208','Ranging请求次数(求和)','xinwei.xinwei_BTS_SERVICE');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS00209','Ranging应答次数(求和)','xinwei.xinwei_BTS_SERVICE');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS002010','基站CPU占用率(平均)','xinwei.xinwei_BTS_OTHER');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS002011','基站CPU占用率(最大)','xinwei.xinwei_BTS_OTHER');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS002012','基站CPU占用率(最小)','xinwei.xinwei_BTS_OTHER');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS002013','基站内存占用率(平均)','xinwei.xinwei_BTS_OTHER');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS002014','基站内存占用率(最大)','xinwei.xinwei_BTS_OTHER');
upsert into xinwei.res_kpi(id,name,dsttable) values('BTS002015','基站内存占用率(最小)','xinwei.xinwei_BTS_OTHER');

upsert into xinwei.res_kpi(id,name,dsttable) values('SAG0010', '个呼呼叫综合话务量','xinwei.xinwei_SAG_TAG0001');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG0011', '个呼呼叫综合接通率','xinwei.xinwei_SAG_TAG0001');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG0012', '个呼呼叫综合应答率','xinwei.xinwei_SAG_TAG0001');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG0013', '个呼呼叫综合应答时长','xinwei.xinwei_SAG_TAG0001');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG0014', '个呼呼叫综合应答次数','xinwei.xinwei_SAG_TAG0001');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG0015', '个呼呼叫综合掉话率','xinwei.xinwei_SAG_TAG0001');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG0016', '个呼呼叫综合掉话次数','xinwei.xinwei_SAG_TAG0001');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG0017', '个呼呼叫综合话务掉话比','xinwei.xinwei_SAG_TAG0001');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG0018', '个呼呼叫综合被叫忙次数','xinwei.xinwei_SAG_TAG0001');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG0019', '个呼呼叫综合久叫不应次数', 'xinwei.xinwei_SAG_TAG0001');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG0011', '个呼呼叫综合被叫拒接次数', 'xinwei.xinwei_SAG_TAG0001');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG00111','个呼呼叫综合其他失败原因次数','xinwei.xinwei_SAG_TAG0001');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG00112','个呼呼叫综合试呼次数','xinwei.xinwei_SAG_TAG0001');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG00113','个呼呼叫综合移动用户不可达次数', 'xinwei.xinwei_SAG_TAG0001');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG00114','个呼呼叫综合L3分配失败次数','xinwei.xinwei_SAG_TAG0001');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG00115','个呼呼叫综合空中接口链路故障次数','xinwei.xinwei_SAG_TAG0001');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG00116','个呼呼叫综合L3分配响应发送次数', 'xinwei.xinwei_SAG_TAG0001');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG00117','个呼呼叫综合空中接口链路故障次数','xinwei.xinwei_SAG_TAG0001');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG0020', '个呼呼叫局内话务量','xinwei.xinwei_SAG_TAG0002');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG0021', '个呼呼叫局内接通率','xinwei.xinwei_SAG_TAG0002');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG0022', '个呼呼叫局内应答率','xinwei.xinwei_SAG_TAG0002');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG0023', '个呼呼叫局内应答时长','xinwei.xinwei_SAG_TAG0002');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG0024', '个呼呼叫局内应答次数','xinwei.xinwei_SAG_TAG0002');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG0025', '个呼呼叫局内掉话率','xinwei.xinwei_SAG_TAG0002');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG0026', '个呼呼叫局内掉话次数','xinwei.xinwei_SAG_TAG0002');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG0027', '个呼呼叫局内话务掉话比','xinwei.xinwei_SAG_TAG0002');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG0028', '个呼呼叫局内被叫忙次数','xinwei.xinwei_SAG_TAG0002');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG0029', '个呼呼叫局内久叫不应次数','xinwei.xinwei_SAG_TAG0002');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG00210','个呼呼叫局内被叫拒接次数','xinwei.xinwei_SAG_TAG0002');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG00211','个呼呼叫局内其他失败原因次数','xinwei.xinwei_SAG_TAG0002');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG00212','个呼呼叫局内试呼次数','xinwei.xinwei_SAG_TAG0002');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG0030', '个呼呼叫出局话务量','xinwei.xinwei_SAG_TAG0003');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG0031', '个呼呼叫出局接通率','xinwei.xinwei_SAG_TAG0003');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG0032', '个呼呼叫出局应答率','xinwei.xinwei_SAG_TAG0003');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG0033', '个呼呼叫出局应答时长','xinwei.xinwei_SAG_TAG0003');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG0034', '个呼呼叫出局应答次数','xinwei.xinwei_SAG_TAG0003');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG0035', '个呼呼叫出局掉话率','xinwei.xinwei_SAG_TAG0003');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG0036', '个呼呼叫出局掉话次数','xinwei.xinwei_SAG_TAG0003');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG0037', '个呼呼叫出局话务掉话比','xinwei.xinwei_SAG_TAG0003');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG0038', '个呼呼叫出局被叫忙次数','xinwei.xinwei_SAG_TAG0003');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG0039', '个呼呼叫出局久叫不应次数','xinwei.xinwei_SAG_TAG0003');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG00310','个呼呼叫出局被叫拒接次数','xinwei.xinwei_SAG_TAG0003');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG00311','个呼呼叫出局其他失败原因次数','xinwei.xinwei_SAG_TAG0003');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG00312','个呼呼叫出局试呼次数','xinwei.xinwei_SAG_TAG0003');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG0040', '个呼呼叫入局话务量','xinwei.xinwei_SAG_TAG0004');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG0041', '个呼呼叫入局接通率','xinwei.xinwei_SAG_TAG0004');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG0042', '个呼呼叫入局应答率','xinwei.xinwei_SAG_TAG0004');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG0043', '个呼呼叫入局应答时长','xinwei.xinwei_SAG_TAG0004');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG0044', '个呼呼叫入局应答次数','xinwei.xinwei_SAG_TAG0004');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG0045', '个呼呼叫入局掉话率','xinwei.xinwei_SAG_TAG0004');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG0046', '个呼呼叫入局掉话次数','xinwei.xinwei_SAG_TAG0004');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG0047', '个呼呼叫入局话务掉话比','xinwei.xinwei_SAG_TAG0004');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG0048', '个呼呼叫入局被叫忙次数','xinwei.xinwei_SAG_TAG0004');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG0049', '个呼呼叫入局久叫不应次数','xinwei.xinwei_SAG_TAG0004');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG00410','个呼呼叫入局被叫拒接次数','xinwei.xinwei_SAG_TAG0004');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG00411','个呼呼叫入局其他失败原因次数','xinwei.xinwei_SAG_TAG0004');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG00412','个呼呼叫入局试呼次数','xinwei.xinwei_SAG_TAG0004');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG0050', '个呼呼叫McWiLL网内呼出话务量','xinwei.xinwei_SAG_TAG0005');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG0051', '个呼呼叫McWiLL网内呼出接通率','xinwei.xinwei_SAG_TAG0005');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG0052', '个呼呼叫McWiLL网内呼出应答率','xinwei.xinwei_SAG_TAG0005');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG0053', '个呼呼叫McWiLL网内呼出应答时长', 'xinwei.xinwei_SAG_TAG0005');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG0054', '个呼呼叫McWiLL网内呼出应答次数', 'xinwei.xinwei_SAG_TAG0005');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG0055', '个呼呼叫McWiLL网内呼出掉话率','xinwei.xinwei_SAG_TAG0005');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG0056', '个呼呼叫McWiLL网内呼出掉话次数', 'xinwei.xinwei_SAG_TAG0005');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG0057', '个呼呼叫McWiLL网内呼出话务掉话比','xinwei.xinwei_SAG_TAG0005');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG0058', '个呼呼叫McWiLL网内呼出被叫忙次数','xinwei.xinwei_SAG_TAG0005');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG0059', '个呼呼叫McWiLL网内呼出久叫不应次数','xinwei.xinwei_SAG_TAG0005');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG00510','个呼呼叫McWiLL网内呼出被叫拒接次数','xinwei.xinwei_SAG_TAG0005');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG00511','个呼呼叫McWiLL网内呼出其他失败原因次数','xinwei.xinwei_SAG_TAG0005');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG00512','个呼呼叫McWiLL网内呼出试呼次数', 'xinwei.xinwei_SAG_TAG0005');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG0060', '个呼呼叫McWiLL网内呼入话务量','xinwei.xinwei_SAG_TAG0006');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG0061', '个呼呼叫McWiLL网内呼入接通率','xinwei.xinwei_SAG_TAG0006');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG0062', '个呼呼叫McWiLL网内呼入应答率','xinwei.xinwei_SAG_TAG0006');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG0063', '个呼呼叫McWiLL网内呼入应答时长', 'xinwei.xinwei_SAG_TAG0006');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG0064', '个呼呼叫McWiLL网内呼入应答次数', 'xinwei.xinwei_SAG_TAG0006');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG0065', '个呼呼叫McWiLL网内呼入掉话率','xinwei.xinwei_SAG_TAG0006');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG0066', '个呼呼叫McWiLL网内呼入掉话次数', 'xinwei.xinwei_SAG_TAG0006');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG0067', '个呼呼叫McWiLL网内呼入话务掉话比','xinwei.xinwei_SAG_TAG0006');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG0068', '个呼呼叫McWiLL网内呼入被叫忙次数','xinwei.xinwei_SAG_TAG0006');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG0069', '个呼呼叫McWiLL网内呼入久叫不应次数','xinwei.xinwei_SAG_TAG0006');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG00610','个呼呼叫McWiLL网内呼入被叫拒接次数','xinwei.xinwei_SAG_TAG0006');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG00611','个呼呼叫McWiLL网内呼入其他失败原因次数','xinwei.xinwei_SAG_TAG0006');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG00612','个呼呼叫McWiLL网内呼入试呼次数', 'xinwei.xinwei_SAG_TAG0006');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG0070', '个呼呼叫市话呼出话务量','xinwei.xinwei_SAG_TAG0007');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG0071', '个呼呼叫市话呼出接通率','xinwei.xinwei_SAG_TAG0007');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG0072', '个呼呼叫市话呼出应答率','xinwei.xinwei_SAG_TAG0007');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG0073', '个呼呼叫市话呼出应答时长','xinwei.xinwei_SAG_TAG0007');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG0074', '个呼呼叫市话呼出应答次数','xinwei.xinwei_SAG_TAG0007');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG0075', '个呼呼叫市话呼出掉话率','xinwei.xinwei_SAG_TAG0007');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG0076', '个呼呼叫市话呼出掉话次数','xinwei.xinwei_SAG_TAG0007');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG0077', '个呼呼叫市话呼出话务掉话比','xinwei.xinwei_SAG_TAG0007');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG0078', '个呼呼叫市话呼出被叫忙次数','xinwei.xinwei_SAG_TAG0007');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG0079', '个呼呼叫市话呼出久叫不应次数','xinwei.xinwei_SAG_TAG0007');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG00710','个呼呼叫市话呼出被叫拒接次数','xinwei.xinwei_SAG_TAG0007');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG00711','个呼呼叫市话呼出其他失败原因次数','xinwei.xinwei_SAG_TAG0007');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG00712','个呼呼叫市话呼出试呼次数','xinwei.xinwei_SAG_TAG0007');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG0080', '个呼呼叫市话呼入话务量','xinwei.xinwei_SAG_TAG0008');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG0081', '个呼呼叫市话呼入接通率','xinwei.xinwei_SAG_TAG0008');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG0082', '个呼呼叫市话呼入应答率','xinwei.xinwei_SAG_TAG0008');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG0083', '个呼呼叫市话呼入应答时长','xinwei.xinwei_SAG_TAG0008');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG0084', '个呼呼叫市话呼入应答次数','xinwei.xinwei_SAG_TAG0008');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG0085', '个呼呼叫市话呼入掉话率','xinwei.xinwei_SAG_TAG0008'); 
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG0086', '个呼呼叫市话呼入掉话次数','xinwei.xinwei_SAG_TAG0008');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG0087', '个呼呼叫市话呼入话务掉话比','xinwei.xinwei_SAG_TAG0008');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG0088', '个呼呼叫市话呼入被叫忙次数','xinwei.xinwei_SAG_TAG0008');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG0089', '个呼呼叫市话呼入久叫不应次数','xinwei.xinwei_SAG_TAG0008');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG00810','个呼呼叫市话呼入被叫拒接次数','xinwei.xinwei_SAG_TAG0008');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG00811','个呼呼叫市话呼入其他失败原因次数','xinwei.xinwei_SAG_TAG0008');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG00812','个呼呼叫市话呼入试呼次数','xinwei.xinwei_SAG_TAG0008');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG0090', '个呼呼叫本地呼出话务量','xinwei.xinwei_SAG_TAG0009');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG0091', '个呼呼叫本地呼出接通率','xinwei.xinwei_SAG_TAG0009');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG0092', '个呼呼叫本地呼出应答率','xinwei.xinwei_SAG_TAG0009');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG0093', '个呼呼叫本地呼出应答时长','xinwei.xinwei_SAG_TAG0009'); 
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG0094', '个呼呼叫本地呼出应答次数','xinwei.xinwei_SAG_TAG0009'); 
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG0095', '个呼呼叫本地呼出掉话率','xinwei.xinwei_SAG_TAG0009');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG0096', '个呼呼叫本地呼出掉话次数','xinwei.xinwei_SAG_TAG0009');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG0097', '个呼呼叫本地呼出话务掉话比','xinwei.xinwei_SAG_TAG0009');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG0098', '个呼呼叫本地呼出被叫忙次数','xinwei.xinwei_SAG_TAG0009');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG0099', '个呼呼叫本地呼出久叫不应次数','xinwei.xinwei_SAG_TAG0009');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG00910','个呼呼叫本地呼出被叫拒接次数','xinwei.xinwei_SAG_TAG0009');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG00911','个呼呼叫本地呼出其他失败原因次数','xinwei.xinwei_SAG_TAG0009');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG00912','个呼呼叫本地呼出试呼次数', 'xinwei.xinwei_SAG_TAG0009');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG00100','个呼呼叫本地呼入话务量','xinwei.xinwei_SAG_TAG0010');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG00101','个呼呼叫本地呼入接通率','xinwei.xinwei_SAG_TAG0010'); 
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG00102','个呼呼叫本地呼入应答率','xinwei.xinwei_SAG_TAG0010'); 
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG00103','个呼呼叫本地呼入应答时长','xinwei.xinwei_SAG_TAG0010');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG00104','个呼呼叫本地呼入应答次数','xinwei.xinwei_SAG_TAG0010');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG00105','个呼呼叫本地呼入掉话率','xinwei.xinwei_SAG_TAG0010'); 
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG00106','个呼呼叫本地呼入掉话次数','xinwei.xinwei_SAG_TAG0010');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG00107','个呼呼叫本地呼入话务掉话比','xinwei.xinwei_SAG_TAG0010');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG00108','个呼呼叫本地呼入被叫忙次数','xinwei.xinwei_SAG_TAG0010');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG00109','个呼呼叫本地呼入久叫不应次数','xinwei.xinwei_SAG_TAG0010');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG001010','个呼呼叫本地呼入被叫拒接次数','xinwei.xinwei_SAG_TAG0010');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG001011','个呼呼叫本地呼入其他失败原因次数','xinwei.xinwei_SAG_TAG0010');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG001012','个呼呼叫本地呼入试呼次数', 'xinwei.xinwei_SAG_TAG0010');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG00110','个呼呼叫国内长途呼出话务量','xinwei.xinwei_SAG_TAG0011');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG00111','个呼呼叫国内长途呼出接通率','xinwei.xinwei_SAG_TAG0011');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG00112','个呼呼叫国内长途呼出应答率','xinwei.xinwei_SAG_TAG0011');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG00113','个呼呼叫国内长途呼出应答时长','xinwei.xinwei_SAG_TAG0011');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG00114','个呼呼叫国内长途呼出应答次数','xinwei.xinwei_SAG_TAG0011');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG00115','个呼呼叫国内长途呼出掉话率','xinwei.xinwei_SAG_TAG0011');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG00116','个呼呼叫国内长途呼出掉话次数','xinwei.xinwei_SAG_TAG0011');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG00117','个呼呼叫国内长途呼出话务掉话比', 'xinwei.xinwei_SAG_TAG0011');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG00118','个呼呼叫国内长途呼出被叫忙次数', 'xinwei.xinwei_SAG_TAG0011');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG00119','个呼呼叫国内长途呼出久叫不应次数','xinwei.xinwei_SAG_TAG0011');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG001110','个呼呼叫国内长途呼出被叫拒接次数','xinwei.xinwei_SAG_TAG0011');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG001111','个呼呼叫国内长途呼出其他失败原因次数', 'xinwei.xinwei_SAG_TAG0011');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG001112','个个呼呼叫国内长途呼出试呼次数', 'xinwei.xinwei_SAG_TAG0011');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG00120','个呼呼叫国内长途呼入话务量','xinwei.xinwei_SAG_TAG0012');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG00121','个呼呼叫国内长途呼入接通率','xinwei.xinwei_SAG_TAG0012');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG00122','个呼呼叫国内长途呼入应答率','xinwei.xinwei_SAG_TAG0012');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG00123','个呼呼叫国内长途呼入应答时长','xinwei.xinwei_SAG_TAG0012');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG00124','个呼呼叫国内长途呼入应答次数','xinwei.xinwei_SAG_TAG0012');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG00125','个呼呼叫国内长途呼入掉话率','xinwei.xinwei_SAG_TAG0012');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG00126','个呼呼叫国内长途呼入掉话次数','xinwei.xinwei_SAG_TAG0012');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG00127','个呼呼叫国内长途呼入话务掉话比', 'xinwei.xinwei_SAG_TAG0012');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG00128','个呼呼叫国内长途呼入被叫忙次数', 'xinwei.xinwei_SAG_TAG0012');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG00129','个呼呼叫国内长途呼入久叫不应次数','xinwei.xinwei_SAG_TAG0012');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG001210','个呼呼叫国内长途呼入被叫拒接次数','xinwei.xinwei_SAG_TAG0012');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG001211','个呼呼叫国内长途呼入其他失败原因次数', 'xinwei.xinwei_SAG_TAG0012');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG001212','个呼呼叫国内长途呼入试呼次数','xinwei.xinwei_SAG_TAG0012');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG00130','个呼呼叫国际长途呼出话务量','xinwei.xinwei_SAG_TAG0013');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG00131','个呼呼叫国际长途呼出接通率','xinwei.xinwei_SAG_TAG0013');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG00132','个呼呼叫国际长途呼出应答率','xinwei.xinwei_SAG_TAG0013');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG00133','个呼呼叫国际长途呼出应答时长','xinwei.xinwei_SAG_TAG0013');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG00134','个呼呼叫国际长途呼出应答次数','xinwei.xinwei_SAG_TAG0013');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG00135','个呼呼叫国际长途呼出掉话率','xinwei.xinwei_SAG_TAG0013');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG00136','个呼呼叫国际长途呼出掉话次数','xinwei.xinwei_SAG_TAG0013');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG00137','个呼呼叫国际长途呼出话务掉话比', 'xinwei.xinwei_SAG_TAG0013');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG00138','个呼呼叫国际长途呼出被叫忙次数', 'xinwei.xinwei_SAG_TAG0013');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG00139','个呼呼叫国际长途呼出久叫不应次数','xinwei.xinwei_SAG_TAG0013');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG001310','个呼呼叫国际长途呼出被叫拒接次数','xinwei.xinwei_SAG_TAG0013');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG001311','个呼呼叫国际长途呼出其他失败原因次数', 'xinwei.xinwei_SAG_TAG0013'); 
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG001312','个呼呼叫国际长途呼出试呼次数','xinwei.xinwei_SAG_TAG0013');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG00140','个呼呼叫国际长途呼入话务量','xinwei.xinwei_SAG_TAG0014');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG00141','个呼呼叫国际长途呼入接通率','xinwei.xinwei_SAG_TAG0014');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG00142','个呼呼叫国际长途呼入应答率','xinwei.xinwei_SAG_TAG0014');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG00143','个呼呼叫国际长途呼入应答时长','xinwei.xinwei_SAG_TAG0014');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG00144','个呼呼叫国际长途呼入应答次数','xinwei.xinwei_SAG_TAG0014');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG00145','个呼呼叫国际长途呼入掉话率','xinwei.xinwei_SAG_TAG0014');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG00146','个呼呼叫国际长途呼入掉话次数','xinwei.xinwei_SAG_TAG0014');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG00147','个呼呼叫国际长途呼入话务掉话比', 'xinwei.xinwei_SAG_TAG0014');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG00148','个呼呼叫国际长途呼入被叫忙次数', 'xinwei.xinwei_SAG_TAG0014');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG00149','个呼呼叫国际长途呼入久叫不应次数','xinwei.xinwei_SAG_TAG0014');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG001410','个呼呼叫国际长途呼入被叫拒接次数','xinwei.xinwei_SAG_TAG0014');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG001411','个呼呼叫国际长途呼入其他失败原因次数', 'xinwei.xinwei_SAG_TAG0014');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG001412','个个呼呼叫国际长途呼入试呼次数', 'xinwei.xinwei_SAG_TAG0014');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG00150','个呼呼叫特服呼出话务量','xinwei.xinwei_SAG_TAG0015');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG00151','个呼呼叫特服呼出接通率','xinwei.xinwei_SAG_TAG0015');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG00152','个呼呼叫特服呼出应答率','xinwei.xinwei_SAG_TAG0015');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG00153','个呼呼叫特服呼出应答时长','xinwei.xinwei_SAG_TAG0015');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG00154','个呼呼叫特服呼出应答次数','xinwei.xinwei_SAG_TAG0015');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG00155','个呼呼叫特服呼出掉话率','xinwei.xinwei_SAG_TAG0015');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG00156','个呼呼叫特服呼出掉话次数','xinwei.xinwei_SAG_TAG0015');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG00157','个呼呼叫特服呼出话务掉话比','xinwei.xinwei_SAG_TAG0015');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG00158','个呼呼叫特服呼出被叫忙次数','xinwei.xinwei_SAG_TAG0015');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG00159','个呼呼叫特服呼出久叫不应次数','xinwei.xinwei_SAG_TAG0015');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG00151','个呼呼叫特服呼出被叫拒接次数','xinwei.xinwei_SAG_TAG0015');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG001511','个呼呼叫特服呼出其他失败原因次数','xinwei.xinwei_SAG_TAG0015');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG001512','个呼呼叫特服呼出试呼次数','xinwei.xinwei_SAG_TAG0015');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG00160','个呼呼叫指定局向话务量','xinwei.xinwei_SAG_TAG0016');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG00161','个呼呼叫指定局向接通率','xinwei.xinwei_SAG_TAG0016');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG00162','个呼呼叫指定局向应答率','xinwei.xinwei_SAG_TAG0016');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG00163','个呼呼叫指定局向应答时长','xinwei.xinwei_SAG_TAG0016');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG00164','个呼呼叫指定局向应答次数','xinwei.xinwei_SAG_TAG0016');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG00165','个呼呼叫指定局向掉话率','xinwei.xinwei_SAG_TAG0016');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG00166','个呼呼叫指定局向掉话次数','xinwei.xinwei_SAG_TAG0016');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG00167','个呼呼叫指定局向话务掉话比','xinwei.xinwei_SAG_TAG0016');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG00168','个呼呼叫指定局向被叫忙次数','xinwei.xinwei_SAG_TAG0016');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG00169','个呼呼叫指定局向久叫不应次数','xinwei.xinwei_SAG_TAG0016');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG001610','个呼呼叫指定局向被叫拒接次数','xinwei.xinwei_SAG_TAG0016');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG001611','个呼呼叫指定局向其他失败原因次数','xinwei.xinwei_SAG_TAG0016');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG001612','个呼呼叫指定局向试呼次数','xinwei.xinwei_SAG_TAG0016');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG00170','个呼呼叫指定基站话务量','xinwei.xinwei_SAG_TAG0017');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG00171','个呼呼叫指定基站接通率','xinwei.xinwei_SAG_TAG0017');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG00172','个呼呼叫指定基站应答率','xinwei.xinwei_SAG_TAG0017');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG00173','个呼呼叫指定基站应答时长','xinwei.xinwei_SAG_TAG0017');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG00174','个呼呼叫指定基站应答次数','xinwei.xinwei_SAG_TAG0017');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG00175','个呼呼叫指定基站掉话率','xinwei.xinwei_SAG_TAG0017');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG00176','个呼呼叫指定基站掉话次数','xinwei.xinwei_SAG_TAG0017');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG00177','个呼呼叫指定基站话务掉话比','xinwei.xinwei_SAG_TAG0017');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG00178','个呼呼叫指定基站被叫忙次数','xinwei.xinwei_SAG_TAG0017');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG00179','个呼呼叫指定基站久叫不应次数','xinwei.xinwei_SAG_TAG0017');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG001710','个呼呼叫指定基站被叫拒接次数','xinwei.xinwei_SAG_TAG0017');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG001711','个呼呼叫指定基站其他失败原因次数','xinwei.xinwei_SAG_TAG0017');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG001712','个呼呼叫指定基站试呼次数', 'xinwei.xinwei_SAG_TAG0017');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG001713','个呼呼叫指定基站语音寻呼请求次数','xinwei.xinwei_SAG_TAG0017'); 
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG001714','个呼呼叫指定基站语音寻呼成功次数','xinwei.xinwei_SAG_TAG0017');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG001715','个呼呼叫指定基站语音寻呼成功率', 'xinwei.xinwei_SAG_TAG0017');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG00180','个呼补充业务无条件前转次数','xinwei.xinwei_SAG_TAG0018');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG00181','个呼补充业务遇忙前转次数', 'xinwei.xinwei_SAG_TAG0018');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG00182','个呼补充业务无应答前转次数','xinwei.xinwei_SAG_TAG0018'); 
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG00183','个呼补充业务不可及前转次数','xinwei.xinwei_SAG_TAG0018');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG00184','个呼补充业务拍叉前转次数', 'xinwei.xinwei_SAG_TAG0018'); 
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG00185','个呼补充业务N方会议次数','xinwei.xinwei_SAG_TAG0018'); 
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG00186','个呼补充业务一呼双响次数', 'xinwei.xinwei_SAG_TAG0018'); 
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG00187','个呼补充业务一号双机次数', 'xinwei.xinwei_SAG_TAG0018'); 
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG00188','个呼补充业务被叫寻呼不到漏呼通知次数', 'xinwei.xinwei_SAG_TAG0018');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG00189','个呼补充业务被叫忙漏呼通知次数', 'xinwei.xinwei_SAG_TAG0018');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG001810','个呼补充业务被叫关机漏呼通知次数','xinwei.xinwei_SAG_TAG0018');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG001811','个呼补充业务呼叫等待次数', 'xinwei.xinwei_SAG_TAG0018');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG001812','个呼补充业务呼叫试呼次数', 'xinwei.xinwei_SAG_TAG0018');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG00190','短信MO成功率','xinwei.xinwei_SAG_TAG0019');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG00191','短信MO成功次数','xinwei.xinwei_SAG_TAG0019');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG00192','短信MO次数','xinwei.xinwei_SAG_TAG0019'); 
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG00193','短信MT成功率','xinwei.xinwei_SAG_TAG0019');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG00194','短信MT成功次数','xinwei.xinwei_SAG_TAG0019');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG00195','短信MT次数','xinwei.xinwei_SAG_TAG0019');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG00250','语音注册成功率','xinwei.xinwei_SAG_TAG0025');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG00251','语音注册成功次数','xinwei.xinwei_SAG_TAG0025');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG00252','语音注册次数','xinwei.xinwei_SAG_TAG0025');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG00260','非语音注册用户登录成功率','xinwei.xinwei_SAG_TAG0026');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG00261','非语音注册用户登录成功次数','xinwei.xinwei_SAG_TAG0026');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG00262','非语音注册用户登录次数','xinwei.xinwei_SAG_TAG0026');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG00263','非语音注册数据业务OAM注册成功率','xinwei.xinwei_SAG_TAG0026');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG00264','非语音注册数据业务OAM注册成功次数', 'xinwei.xinwei_SAG_TAG0026');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG00265','非语音注册数据业务OAM注册次数','xinwei.xinwei_SAG_TAG0026');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG00270','鉴权成功率','xinwei.xinwei_SAG_TAG0027');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG00271','鉴权成功次数','xinwei.xinwei_SAG_TAG0027');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG00272','鉴权请求次数','xinwei.xinwei_SAG_TAG0027');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG00280','切换成功率','xinwei.xinwei_SAG_TAG0028');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG00281','切换成功通话次数','xinwei.xinwei_SAG_TAG0028');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG00282','切换请求次数','xinwei.xinwei_SAG_TAG0028');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG00340','TSP板CPU最大占用率','xinwei.xinwei_SAG_TAG0034');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG00341','TSP板CPU平均占用率','xinwei.xinwei_SAG_TAG0034');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG00350','NSP板CPU最大占用率','xinwei.xinwei_SAG_TAG0034');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG00351','NSP板CPU平均占用率','xinwei.xinwei_SAG_TAG0034');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG00400','TSP板内存最大占用量','xinwei.xinwei_SAG_TAG0040');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG00401','TSP板内存平均占用量','xinwei.xinwei_SAG_TAG0040');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG00410','NSP板内存最大占用量','xinwei.xinwei_SAG_TAG0041');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG00411','NSP板内存平均占用量','xinwei.xinwei_SAG_TAG0041');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG00480','VLR中R5用户数','xinwei.xinwei_SAG_TAG0048');
upsert into xinwei.res_kpi(id,name,dsttable) values('SAG00481','VLR中R6用户数','xinwei.xinwei_SAG_TAG0048');

